apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-cluster
  region: eu-central-1

nodeGroups:
  - name: hfworker
    instanceType: m5.2xlarge
    desiredCapacity: 3
    volumeSize: 60
  - name: hfmaster
    instanceType: m5.2xlarge
    desiredCapacity: 1
    volumeSize: 300

vpc:
  cidr: 192.168.0.0/16