apiVersion: v1
kind: PersistentVolume
metadata:
  name: juicefs-pv
  namespace: {{ .Values.namespace }}
  labels:
    juicefs-name: juicefs-pv
spec:
  capacity:
    storage: {{ .Values.pv.capacity.storage }}
  volumeMode: Filesystem
  accessModes: {{ .Values.pv.accessModes | toYaml | nindent 4 }}
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - writeback
    - writeback_cache
    - free-space-ratio=0.5
    - max-uploads=200
    - buffer-size=3000
    - cache-dir=/var/jfsCache
    - cache-size=20240
    - prefetch=16
    - allow_other
  csi:
    driver: csi.juicefs.com
    volumeHandle: hyperflow
    fsType: juicefs
    nodePublishSecretRef:
      name: juicefs-sc-secret
      namespace: kube-system