apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: {{ .Values.namespace }}
spec:
  accessModes: {{ .Values.pv.accessModes | toYaml | nindent 4 }}
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.pv.capacity.storage }}
  selector:
    matchLabels:
      juicefs-name: juicefs-pv