apiVersion: hyperflow.agh.edu.pl/v1
kind: WorkerPool
metadata:
  name: mbackground
spec:
  taskType: mBackground
  image: hyperflowwms/montage2-worker:je-1.3.0
  rabbitHostname: rabbitmq.default
  prometheusUrl: http://monitoring-prometheus.default:9090
  redisUrl: redis://redis:6379
  minReplicaCount: 0
  maxReplicaCount: 50
  initialResources:
    requests:
      cpu: "0.5"
      memory: "524288000"