apiVersion: v1
kind: Service
metadata:
  name: hyperflow-standalone-autoscaler
spec:
  ports:
    - name: hyperflow-standalone-autoscaler
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    app: hyperflow
    name: hyperflow-standalone-autoscaler
    component: hyperflow-standalone-autoscaler
