apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  accessModes: {{ .Values.pv.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pv.capacity.storage }}
